services:
  streamlit:
    build: .
    container_name: youtube-analytics-streamlit
    command: python -m debugpy --listen 0.0.0.0:5678 -m streamlit run streamlit_app.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
      - "5678:5678"
    volumes:
      - ./app:/app
      - ./logs:/app/logs
      - ./models:/app/models
    environment:
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - COMMENT_LIMIT=${COMMENT_LIMIT}
    networks:
      - youtube-analytics-network

  app:
    build: .
    container_name: youtube-analytics-app
    command: sleep infinity
    tty: true
    volumes:
      - ./app:/app
      - ./logs:/app/logs
      - ./models:/app/models
    environment:
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - COMMENT_LIMIT=${COMMENT_LIMIT}
    networks:
      - youtube-analytics-network

networks:
  youtube-analytics-network:
    driver: bridge
